config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "bins#index"
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :bins, only:[:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bin.rb
class Bin < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :bin_categories, dependent: :destroy
  has_many :categories, through: :bin_categories
  has_many_attached :photos
  validates :name, presence: true
end

app/models/bin_category.rb
class BinCategory < ApplicationRecord
  belongs_to :category
  belongs_to :bin
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bin_categories
  has_many :bins, through: :bin_categories
  validates :name, presence: true
  def icon
    case name
    when "burnable" then "jpic-kanen"
    when "pet bottle" then "jpic-pettobotoru"
    when "unburnable" then "jpic-kaki-genkin"
    else
      "jpic-kan"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bins, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(bins_url)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bin_categories_controller.rb
class BinCategoriesController < ApplicationController
end

app/controllers/bins_controller.rb
require 'exiftool'
require 'open-uri'
class BinsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_bin, only: [:show, :destroy]

  def index
    @bins = policy_scope(Bin)

    @bin = Bin.new
    if params[:query].present?
      # @bins = Bin.where(category: params[:query])
      @bins = Bin.joins(bin_categories: :category).where(categories: {name: params[:query]})
    end
    if params[:lat].present?
      @bins = @bins.geocoded.near([params[:lat], params[:lng]], 1)
    end
    @markers = @bins.geocoded.map do |bin|
      {
        lat: bin.latitude,
        lng: bin.longitude,
        popup_window_html: render_to_string(partial: "popup_window", locals: { bin: bin }),
        marker_html: render_to_string(partial: "marker")
      }
    end
    @categories = Category.all
  end

  def show
    authorize @bin
  end

  def create
    @bin = Bin.new(bin_params)
    @bin.user = current_user
    location = read_coordinates(bin_params[:photos].last.tempfile.path)
    @bin.latitude = location[:latitude]
    @bin.longitude = location[:longitude]


    authorize @bin
    if @bin.save
      redirect_to bins_url(lat: @bin.latitude, lng: @bin.longitude), notice: "Bin was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  #   authorize @bin
  # end

  # def update
  #   authorize @bin
  # end

  def destroy
    authorize @bin
    @bin.destroy
    redirect_to bins_url, notice: "Bin was successfully destroyed."
  end

  private

  def set_bin
    @bin = Bin.find(params[:id])
  end

  def bin_params
    # params.require(:bin).permit(:name, :address, category_ids: [], photos: [])
    params.require(:bin).permit(:name, category_ids: [], photos: [])
  end

  def read_location_from_cloudinary(image_url)
    # Download the image from Google Photos and save it to a local file
    image_data = URI.open(image_url).read
    File.open('image.jpg', 'wb') do |file|
      file.write(image_data)
    end
    # Use Exiftool to read the metadata of the local file
    exiftool = Exiftool.new('image.jpg')

    latitude = exiftool[:gps_latitude]
    longitude = exiftool[:gps_longitude]

    # Print the latitude & longitude
    # puts "Latitude: #{latitude}"
    # puts "Longitude: #{longitude}"

    # Delete the local file
    File.delete('image.jpg')
    {
      latitude: latitude,
      longitude: longitude
    }
  end

  def read_coordinates(image_path)

    # Use Exiftool to read the metadata of the local file
    exiftool = Exiftool.new(image_path)

    latitude = exiftool[:gps_latitude]
    longitude = exiftool[:gps_longitude]

    # Print the latitude & longitude
    # puts "Latitude: #{latitude}"
    # puts "Longitude: #{longitude}"

    {
      latitude: latitude,
      longitude: longitude
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bins/_marker.html.erb
<div class = "custom-markers">
  <%= image_tag "bins.png", height: 30, width: 30, alt: "Logo" %>
</div>

app/views/bins/_new_bin_popup.html.erb
<!-- Modal -->
<div class="modal fade" id="popupModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container mt-4">
          <%= simple_form_for @bin do |f| %>
            <%= f.input :name, html5: true %>
            <%#= f.input :address, html5: true %>
            <%= f.association :categories, multiple: true, collection: Category.all %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <div class="text-center">
              <%= f.submit 'Create a new bin', class: 'btn btn-primary text-light' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bins/_popup_window.html.erb
<div class="card-trip">
  <% if bin.photos.attached? %>
    <%= cl_image_tag(bin.photos.first.key, :format => "jpg") %>
  <% else %>
    <img src="https://www.dulton.jp/img/goods/8/PT_img.jpg" />
  <% end %>
  <div>
    <%= link_to  target: :blank do %>
    <% end %>
    <button data-action="click->map#showAlert" class="alert-btn"><i class="fa-solid fa-circle-exclamation float-end pt-3"></i>
    </button>
  </div>
  <div class="card-trip-infos pb-0">
    <div>
      <h2><%= bin.name %></h2>
      <p class="bin-address"><%= bin.address %></p>
      <% bin.categories.each do |category| %>
        <% if category.name == "pet bottle" %>
          <span class="jpic jpic-pettobotoru"></span>
        <% elsif category.name == "burnable" %>
          <span class="jpic jpic-kanen"></span>
        <% elsif category.name == "unburnable" %>
          <span class="jpic jpic-kaki-genkin"></span>
        <% else %>
          <span class="jpic jpic-kan"></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bins/index.html.erb
<div class="map-container" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-map-markers-value="<%= @markers.to_json %>" >
  <%= form_with url: bins_path(lat: params[:lat], lng: params[:lng]), method: :get, class: "d-flex", data: { controller: 'autosave' } do %>
    <% @categories.each do |category| %>
      <%= check_box_tag 'query[]', category.name, params[:query]&.include?(category.name), id: "category-#{category.id}", class: 'category-selector d-none', data: { action: 'autosave#save' } %>
      <label for="category-<%= category.id %>">
        <span class='jpic <%=category.icon%>'>
          <div class="filter-category-names">
          </span><%= category.name.capitalize %>
        </div>
      </label>
    <% end %>
    <%= text_field_tag 'lat', params[:lat], class: 'category-selector d-none', data: { action: 'autosave#save' } %>
    <%= text_field_tag 'lng', params[:lng], class: 'category-selector d-none', data: { action: 'autosave#save' } %>
  <% end %>
  <div class="mapbox" style="width: 100%;" data-map-target="canvas">
  </div>
  <div class="alert alert-warning alert-dismissible fade" data-map-target="alert" role="alert">
    <strong>Thanks! Your report has been submitted.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <div class="footer d-flex justify-content-between" data-darkmode-target="footer">
    <!-- Button trigger modal -->
    <button type="button" class="btn-socials btn-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fa-solid fa-share-nodes"></i>
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Share & Follow</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="footer-links">
              <a href="https://www.instagram.com/supkev/" target="_blank"><i class="fab fa-instagram"></i></a>
              <a href="https://www.facebook.com/kevin.s.tsai" target="_blank"><i class="fab fa-facebook"></i></a>
              <a href="https://twitter.com/supkev" target="_blank"><i class="fab fa-twitter"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Button trigger modal -->
    <button type="button" data-bs-toggle="modal" data-bs-target="#popupModal" class="add-bin-icon-btn">
      <%= image_tag "card_photo/add_bin.png", class: "add-bin-icon" %>
    </button>
    <%= render 'bins/new_bin_popup' %>
    <div>
      <i class="fa-solid fa-eye btn-toggle" data-action="click->map#toggle click->darkmode#toggle"></i>
    </div>
  </div>
</div>

app/views/bins/new.html.erb
<div class="container mt-4">
  <h2>Create a new bin 🗑</h2>
  <%= simple_form_for @bin do |f| %>
    <%= f.input :name, html5: true %>
    <%#= f.input :address, html5: true %>
    <%= f.association :categories, multiple: true, include_hidden: false %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, include_hidden: false %>
    <%= f.submit 'Create a new bin', class: 'btn btn-info mt-2 text-white' %>
  <% end %>
</div>

app/views/bins/show.html.erb
<%= link_to "Back", bins_path %>
<p>Bin name: <%= @bin.name %></p>
<p>Bin category: <%= @bin.categories.map { |c| c.name.capitalize }.join(", ") %></p>
<p>Bin address: <%= @bin.address %></p>
<!-- [...] -->
<%= button_to "Destroy this bin", @bin, method: :delete if policy(@bin).destroy? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Binfind</title>
    <meta charset="utf-8">
    <%# <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> %>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <!-- HTML Meta Tags -->
    <title>Binfind</title>
    <meta name="description" content="Solving Tokyo residents problem, locating trash bins all over city. In order to keep the city clean and dispose waste in the correct manner.">
    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="Binfind">
    <meta itemprop="description" content="Solving Tokyo residents problem, locating trash bins all over city. In order to keep the city clean and dispose waste in the correct manner.">
    <meta itemprop="image" content="https://res.cloudinary.com/dh7mp7shk/image/upload/v1678936854/Screenshot_2023-03-16_at_12.20.12_PM_y8jwat.png">
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://www.binfind.online">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Binfind">
    <meta property="og:description" content="Solving Tokyo residents problem, locating trash bins all over city. In order to keep the city clean and dispose waste in the correct manner.">
    <meta property="og:image" content="https://res.cloudinary.com/dh7mp7shk/image/upload/v1678936854/Screenshot_2023-03-16_at_12.20.12_PM_y8jwat.png">
    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Binfind">
    <meta name="twitter:description" content="Solving Tokyo residents problem, locating trash bins all over city. In order to keep the city clean and dispose waste in the correct manner.">
    <meta name="twitter:image" content="https://res.cloudinary.com/dh7mp7shk/image/upload/v1678936854/Screenshot_2023-03-16_at_12.20.12_PM_y8jwat.png">
    <!-- Meta Tags Generated via http://heymeta.com -->
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://yannklein.github.io/japan-pictograms/japan-pictograms.css">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body data-controller="darkmode" data-darkmode-target="body">
    <%= render "shared/flashes" %>
    <div>
      <%= render "shared/navbar" %>
      <%= render "shared/display_navigation" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container" data-controller="current-location">
  <div class="banner">
    <div class="about-bin">
      <%= image_tag 'binfind_logo.png', alt: "text", width: '75%', height: 'auto'  %>
      <h6 class="fs-3 text fw-bolder text-white">Looking to dispose your trash?</h6>
      <%= link_to "Find Your Nearest Bin", bins_path, data:{current_location_target:'link'} , class: "btn btn-success",style: 'border-radius: 7px;', type: "button" %>
    </div>
  </div>
  <video autoplay="autoplay" loop="loop" muted defaultMuted playsinline  oncontextmenu="return false;"  preload="auto" class="home-vid">
    <source src="https://res.cloudinary.com/dh7mp7shk/video/upload/v1678239698/background1_idcpsj.mp4" type="video/mp4">
  </video>
</div>

app/views/shared/_display_navigation.erb
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon" data-darkmode-target="navbar">
  <div class="container-fluid">
    <%= link_to bins_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/djzdj5fnx/image/upload/v1677640582/binfind-high-resolution-logo-black-on-transparent-background_sbprnl.png", class: "logo" %>
    <% end %>
    <div id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/djzdj5fnx/image/upload/v1677638682/download_mb9u8c.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a bin", new_bin_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>